### ISSUE TITLE
env0r spits variable values to console in EB

### ISSUE THREAD

**Issue by vix633** [Brightspace/node-env-or#16]
If you use env for any sort of sensitive config, such as credentials and import them via env0r, they end up in the console out.
This is terrible for anyone that ships their logs off somewhere, like cloudwatch.

**Comment by omsmith** [comment]
Yeah, the output was there to make it easy to assess what config was loaded in via the logs, but it's for sure not appropriate for all of the potential values.

Perhaps adding a "private" or "secure" param to adjust the output would make the most sense?
